name: flutter_starter
description: A new Flutter project.

version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.4
  crypto: ^3.0.1
  csv: ^5.0.0
  cupertino_icons: null
  firebase_auth: ^1.0.2
  firebase_core: ^1.0.3
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  geocoder: ^0.2.1
  geolocator: ^7.7.1
  get: ^4.1.3
  get_storage: ^2.0.2
  google_maps_flutter: ^2.1.0
  google_sign_in: ^5.2.1
  http: ^0.13.1
  image_picker: ^0.8.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
    - assets/images/
